version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database-test"
    ports:
      - "3306:3306"
    volumes:
      - /home/adriano/dev/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network
  adminer:
    image: adminer
    ports:
      - 3500:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge